services:
  - type: web
    name: sparx-shadow
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-fix.txt
    startCommand: python app.py
    pythonVersion: 3.11.9
